services:
  # Redis - Démarrage en premier
  redis:
    image: redis:7-alpine
    container_name: numerusx-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --save 900 100
      --loglevel warning
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - numerusx-network

  # Backend - Démarre après Redis
  backend:
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile
    container_name: numerusx-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot reload during development
      - ./app:/code/app
      - ./data:/code/data
      - ./logs:/code/logs
      - ./keys:/code/keys
      - ./models:/code/models
      # Mount .env files so entrypoint can manage them
      - ./.env.example:/code/.env.example
      - ./.env:/code/.env
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/code
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - numerusx-network

  # Frontend - Démarre après Backend
  frontend:
    build:
      context: .
      dockerfile: Docker/frontend/Dockerfile
    container_name: numerusx-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      # Mount the entire numerusx-ui directory for hot reload during development
      - ./numerusx-ui:/app/numerusx-ui
      # Mount logo if needed
      - ./logo.jpg:/app/logo.jpg
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 45s
    networks:
      - numerusx-network

volumes:
  redis_data:
    driver: local

networks:
  numerusx-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16