services:
  backend:
    build:
      context: ../
      dockerfile: Docker/backend/Dockerfile
      args:
        ENVIRONMENT: dev
    container_name: numerusx_backend
    restart: unless-stopped
    volumes:
      - ../data:/app/data
      - ../app:/app/app
      - ../logs:/app/logs
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    env_file:
      - ../.env
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 512M

  frontend:
    build:
      context: ../
      dockerfile: Docker/frontend/Dockerfile
    container_name: numerusx_frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ../.env

  redis:
    image: redis:alpine
    container_name: numerusx_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: