version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: Docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
      - ../data:/app/data
      - ../logs:/app/logs
      - ../keys:/app/keys
      - ../models:/app/models
      # Mount .env file directly for backend to use
      - ../.env:/app/.env 
    env_file:
      - ../.env
    depends_on:
      - redis
    # command: uvicorn app.main:final_asgi_app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app
    # The command in Dockerfile is uvicorn app.main:socket_app ..., which should be correct

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # Mount the entire numerusx-ui directory from host to container
      # This allows the init-frontend.sh script to create files on the host
      # and for live reloading during development.
      - ../numerusx-ui:/app/numerusx-ui
      # We also need to mount the root logo.jpg if init-frontend.sh uses it.
      - ../logo.jpg:/app/logo.jpg 
    # No env_file needed here explicitly if Vite handles .env files within numerusx-ui
    # or if init-frontend.sh doesn't require specific env vars from docker-compose
    depends_on:
      - backend 

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # command: redis-server --save 60 1 --loglevel warning # Example custom command

volumes:
  redis_data: